FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN groupadd -r appuser && useradd -r -g appuser -m -s /bin/bash appuser
USER appuser
WORKDIR /home/appuser
COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt
COPY app.py .
CMD ["python3", "app.py"]